// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCScrLaR2hsaXfz7ywMc5PJLF72jfp8pSs',
    appId: '1:137357279242:web:a7fa9aec13f1651e111ff3',
    messagingSenderId: '137357279242',
    projectId: 'smarthome-52960',
    authDomain: 'smarthome-52960.firebaseapp.com',
    storageBucket: 'smarthome-52960.appspot.com',
    measurementId: 'G-08SDYQGM13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3LThKXKRCIBOY6sfmFWvlmLu8f-graQI',
    appId: '1:137357279242:android:4c4782e82482d052111ff3',
    messagingSenderId: '137357279242',
    projectId: 'smarthome-52960',
    storageBucket: 'smarthome-52960.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgusnHE3AGpyQatKp7Wg65LHfgeDOkCtU',
    appId: '1:137357279242:ios:f401da5c2627aef6111ff3',
    messagingSenderId: '137357279242',
    projectId: 'smarthome-52960',
    storageBucket: 'smarthome-52960.appspot.com',
    iosClientId: '137357279242-u3jme8ls098almrac35r1u04mln10age.apps.googleusercontent.com',
    iosBundleId: 'hit.bme.hu.smartHomeFlutter',
  );
}
